sudo: false
language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 7.1

script:
  - vendor/bin/tester -p php-cgi tests

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
  - travis_retry composer update --no-interaction
